### ISSUE TITLE
gp.zip is not working

### ISSUE THREAD

**Issue by Mensen** [Stanford-STAGES/stanford-stages#13]
In my test run I received an error with some reference to not being able to find the gp\ folder...

This probably has to do with the issue that I cannot open the gp.zip file and extract its contents. When I try to open the zip I get the following error:

![image](https://user-images.githubusercontent.com/6980040/74646226-b521b800-5179-11ea-9876-c72b363b326a.png)

I've tried deleting the file and downloading it again using this [link](https://www.google.com/url?q=http://www.informaton.org/narco/ml/gp.zip&sa=D&ust=1581457104941000)

In the installation guide it says the zip should be 64MB but the zip file is 42MB... the reported size might just be the extracted size, but I thought it was noticeable in case it relates to this problem.

**Comment by RaghavRao** [comment]
I have the same issue on Linux:
```
$ unzip gp.zip 

Archive:  gp.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
```

Tangentially related: ac.zip is only ~750 Mb instead of being 1.2 Gb

**Comment by informaton** [comment]
Yes, that is definitely a problem.  It should be ~64MB.  I will check on the other model files as well.

**Comment by informaton** [comment]
The gp.zip link and file has been updated.  Depending on the units your system uses to show file sizes, it may appear as 64.4 MB or 61.4 MiB.  I'll take a look at the ac.zip file size discrepancy as well.

**Comment by informaton** [comment]
The ac.zip file size should be close to what you are seeing and not 1.0 GB.  I updated the readme file just now.  I'll leave the issue open for a bit longer in case you run into any other issues or if this does not resolve them.

**Comment by RaghavRao** [comment]
Thanks,

gp.zip works now

**Comment by Mensen** [comment]
Perfect! Thanks for looking into this!

The scripts all work now... technically. Now I just have to tinker with the inputs since its not quite producing the expected stages.
