### ISSUE TITLE
Scaling.zip is not found

### ISSUE THREAD

**Issue by RaghavRao** [Stanford-STAGES/stanford-stages#14]
http://www.informaton.org/narco/ml/scaling.zip returns a 404.

Thanks

**Comment by informaton** [comment]
Thanks.  I see what you mean and will check it out.

**Comment by informaton** [comment]
It should work again now.  We should have a second mirror setup to avoid possible downtime in the future.  I'll leave the issue open for now as a reminder to get that done.

**Comment by informaton** [comment]
Sorry for not catching this earlier, but the scaling files are actually in the repository already under the [ml/scaling/](https://github.com/Stanford-STAGES/stanford-stages/tree/master/ml/scaling) path.  So it is no longer necessary to download the scaling.zip files.  Though, I'll leave them up for reference.
