### ISSUE TITLE
Wrong Calculations with python 3.6

### ISSUE THREAD

**Issue by RaghavRao** [Stanford-STAGES/stanford-stages#17]
On Python 3.6.10 with the requirements listed in #15 I get the result:

Score: -0.0287
Diagnosis: Narcolepsy type 1

When the expected results should be.

Score: 0.1658
Diagnosis: Narcolepsy type 1

The links for the hypnodensity image and txt for single and all models are also broken so I cannot compare them, but I did not know if I should make a separate issue for it.

**Comment by informaton** [comment]
I'll check it out.

**Comment by informaton** [comment]
Regarding the classification scores, it looks like you have the same issue reported in #16 and will likely get the expected results once you update your code from the from the master branch.  

I will try to get the other links fixed in the coming week.

**Comment by informaton** [comment]
I fixed links to the previously broken links for the hypnodensity image and staging text file for the single model case and for all models.  Please reopen this issue if you find further trouble with the links.
