### ISSUE TITLE
KeyError: 'stdV'

### ISSUE THREAD

**Issue by GiorgioRicciardiello** [Stanford-STAGES/stanford-stages#36]
When assigning a path to the variable "narco_classifier_path" in the [stanford_stages.json](https://github.com/Stanford-STAGES/stanford-stages/blob/master/stanford_stages.json) file: 

	"narco_classifier_path": "C:\\path\\to\\stanford-stages-master\\ml\\gp"

The following error occurs: 

In [info_narco_features.py](https://github.com/Stanford-STAGES/stanford-stages/blob/master/inf_narco_features.py) lines [243-252] the script opens a pickle file in the scaling folder ("C:\\path\\to\\stanford-stages-master\\ml\\scaling"), a directoy containing as follows should be obtained from the file: 

`scaled = {'meanV': 'value.dtyp(float)' , 'stdV': '... ', 'medianV': '....' , 'rangeV': '....' }`

But the dictionary with the following keys is obtained: 

`scaled.keys() = dict_keys(['meanV', 'scaleV'])`

This throws an error in lines [249-251] as the keys 'stdV', 'medianV' , and 'rangeV' are not present in the dictionary 'scaled'. 

I observe that the variable 'scale_v' is present in line 252 as a commented code line, but it is not an element of the class, as the 'self.' method is not implemented. 
 
I followed a debug to check if there is a pickle file with the expected keys in the scaling folder, although none of them present them. 

What should I do in this situation for being able to complete the narcolepsy diagnosis? Am I setting the wrong folder path to "narco_classifier_path"? 

If in [stanford_stages.json](https://github.com/Stanford-STAGES/stanford-stages/blob/master/stanford_stages.json), "inf_config"{"narco_classifier_path" = ""} is set as "" . The error does not occur the the hypnodensity is generated. 

This is how I verified the information that I had provided: 
```
# scale_pickle_file = os.path.join(self.scale_path, sc_mod + '_scale.p')
scale_pickle_file  = u'C:/path/to/stanford-stages-master/ml/scaling\\ac_rh_ls_lstm_01_scale.p

with open(scale_pickle_file, 'rb') as sca:
    scaled = pickle.load(sca)

scaled.keys()
dict_keys(['meanV', 'scaleV'])
```
Same results in the remaining 15 files in the scaling path equivalent. 

Thanks for the attention.

**Comment by informaton** [comment]
It sounds like you may be mixing the ___main branch___ with models from the ___manuscript branch___ (e.g. [issue 30](https://github.com/Stanford-STAGES/stanford-stages/issues/30)).  

The sleep staging models will work for either branch, however narcolepsy models are only supported in ___manuscript___ branch.  See the readme file [here](https://github.com/Stanford-STAGES/stanford-stages#branches).  

Let me know if that is the case, and that we haven't unwittingly merged the branches.

**Comment by GiorgioRicciardiello** [comment]
Indeed is as you said! I was mixing the two branches. Thank you for the fast response.
