### ISSUE TITLE
link to models doesn't work

### ISSUE THREAD

**Issue by Victor2100** [Stanford-STAGES/stanford-stages#39]
Hi

The link "[www.informaton.org/narco/ml/ac.zip](http://www.informaton.org/narco/ml/ac.zip)" does not work for me. Is there another link og website where it is possible to download the models?

Kind regards
Victor

**Comment by informaton** [comment]
Hi Victor,
There appears to be an issue with how this link was entered into the readme.md file or an update with how github interprets markdown links that is preventing it from working simply by clicking on it.  

You can try copying and pasting the url you listed into the address bar of your browser (that works for me).  

Or this link, without the markdown added, should work by simply clicking on it: 

https://www.informaton.org/narco/ml/ac.zip


Cheers.

**Comment by Victor2100** [comment]
Thank you very much! that seems to work
