### ISSUE TITLE
Filtering will not be done if index is 0

### ISSUE THREAD

**Issue by hsgarciacaballero** [Stanford-STAGES/stanford-stages#9]
Recently, I started running this model with some data of my own and I noticed that for some subjects the model was always predicting awake. After a thorough debugging, I found out the cause of my problem.

### How to reproduce the error

Specify in your JSON configuration object a channel with index 0. Additionally, it might also require that the channel has quite high values (haven't tested exact numbers, but I would say above the values that are filtered out in the "filtering" step).

### How to solve the problem

[In file "inf_hypnodensity.py", method "filtering"](https://github.com/Stanford-STAGES/stanford-stages/blob/49adbd907e7cff71a68cb348074dedfc39c0d397/inf_hypnodensity.py#L273) we can find this:

`if ch_idx:`

This will evaluate to False when index is 0, skipping the filtering of this channel. By just changing it to something similar to what is done in other parts of the code fixes the problem:

`if isinstance(ch_idx, int):`

**Comment by informaton** [comment]
Humberto!  Thank you for this catch and fix.  I'll work on the fix now.

**Comment by informaton** [comment]
I just committed (cf80dd4) the fix, but will leave the issue open for a bit longer in case there are any other comments or related issues.  Thanks again.
